import type { AIProfile } from './profiles';

// A recurring cast of named opponents. Each character is a full AI profile
// (play-style stats + flavor lines) paired with a portrait photo served from
// /avatars/<id>.jpg. If a portrait file is missing, the table falls back to a
// procedurally-drawn face, so the app works before the images are committed.
//
// To add the photos: drop the nine JPGs into app/public/avatars/ using the
// exact filenames in `portrait` below (256x256-ish, square, head centered).
export const CHARACTERS: AIProfile[] = [
  {
    id: 'marco',
    name: 'Marco "The Cigar"',
    shortName: 'Marco',
    portrait: '/avatars/marco.jpg',
    tightness: 0.3,
    aggression: 0.85,
    bluffFrequency: 0.4,
    callingFrequency: 0.55,
    catchphrases: {
      bet: ['Let me raise the stakes.', 'Money talks.'],
      raise: ['I smell weakness.'],
      'all-in': ["Everything. Why not?"],
      fold: ['Take it, kid.'],
      call: ["I'll pay to see it."],
    },
  },
  {
    id: 'eleanor',
    name: 'Eleanor',
    shortName: 'Eleanor',
    portrait: '/avatars/eleanor.jpg',
    tightness: 0.8,
    aggression: 0.45,
    bluffFrequency: 0.05,
    callingFrequency: 0.3,
    catchphrases: {
      fold: ['Patience, dear.', 'Not this time.'],
      bet: ['I rather like this one.'],
      raise: ["Let's make it interesting."],
      call: ["I'll have a look."],
    },
  },
  {
    id: 'vivian',
    name: 'Vivian',
    shortName: 'Vivian',
    portrait: '/avatars/vivian.jpg',
    tightness: 0.7,
    aggression: 0.75,
    bluffFrequency: 0.2,
    callingFrequency: 0.35,
    catchphrases: {
      raise: ['The math favors me.'],
      bet: ['Calculated.'],
      fold: ['Negative expectation.'],
      'all-in': ["I've already run the numbers."],
    },
  },
  {
    id: 'leo',
    name: 'Leo',
    shortName: 'Leo',
    portrait: '/avatars/leo.jpg',
    tightness: 0.2,
    aggression: 0.25,
    bluffFrequency: 0.05,
    callingFrequency: 0.85,
    catchphrases: {
      call: ['Sure, why not!', 'I wanna see it!'],
      check: ['Free card, nice.'],
      bet: ['Feeling lucky!'],
      fold: ['Aw, fine.'],
    },
  },
  {
    id: 'spike',
    name: 'Spike',
    shortName: 'Spike',
    portrait: '/avatars/spike.jpg',
    tightness: 0.15,
    aggression: 0.95,
    bluffFrequency: 0.5,
    callingFrequency: 0.6,
    catchphrases: {
      raise: ['Chaos!', "Let's break it!"],
      'all-in': ['SEND IT!'],
      bet: ['Boom.'],
      fold: ['Whatever.'],
    },
  },
  {
    id: 'bruno',
    name: 'Bruno',
    shortName: 'Bruno',
    portrait: '/avatars/bruno.jpg',
    tightness: 0.35,
    aggression: 0.8,
    bluffFrequency: 0.3,
    callingFrequency: 0.65,
    catchphrases: {
      raise: ['You sure about that?'],
      bet: ['Pay up.'],
      'all-in': ["Don't test me."],
      fold: ['Tch.'],
      call: ["I'm watching you."],
    },
  },
  {
    id: 'danny',
    name: 'Danny',
    shortName: 'Danny',
    portrait: '/avatars/danny.jpg',
    tightness: 0.5,
    aggression: 0.55,
    bluffFrequency: 0.2,
    callingFrequency: 0.5,
    catchphrases: {
      bet: ['Solid spot for a bet.'],
      raise: ['I think I have the best of it.'],
      call: ['Good price, I call.'],
      fold: ['Nice hand, you win.'],
    },
  },
  {
    id: 'tex',
    name: 'Tex',
    shortName: 'Tex',
    portrait: '/avatars/tex.jpg',
    tightness: 0.7,
    aggression: 0.5,
    bluffFrequency: 0.15,
    callingFrequency: 0.4,
    catchphrases: {
      fold: ["Been around too long for that."],
      call: ['I reckon I will.'],
      bet: ['Got a feelin about this one.'],
      raise: ["Let's see what you're made of."],
    },
  },
  {
    id: 'nadia',
    name: 'Nadia',
    shortName: 'Nadia',
    portrait: '/avatars/nadia.jpg',
    tightness: 0.82,
    aggression: 0.55,
    bluffFrequency: 0.05,
    callingFrequency: 0.3,
    catchphrases: {
      fold: ['No.'],
      bet: ['This is strong.'],
      raise: ["I don't bluff."],
      'all-in': ['I have it.'],
    },
  },
];
